# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-04 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(blank=True, max_length=256, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('url', models.CharField(blank=True, max_length=256, null=True)),
                ('order', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
